version: "3.8"
services:
  db:
    image: "mysql:5.7"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--skip-character-set-client-handshake"
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=spaceplayerDB
      - MYSQL_USER=spaceplayer-user
      - MYSQL_PASSWORD=123456789
    ports:
      - "3306:3306"
  backend:
    image: "node:13"
    working_dir: /var/app/backend
    ports:
      - "4000:4000"
      - "9229:9229"
      - "5000:5000"
    command: npm start
    volumes:
      - "./packages/backend:/var/app/backend"
      - "./infra/env_vars:/var/infra/env_vars"

  frontend:
    image: "node:13"
    working_dir: /var/app/frontend
    ports:
      - "3000:3000"
    command: npm start
    stdin_open: true
    volumes:
      - "./packages/frontend:/var/app/frontend"
      - "./infra/env_vars:/var/infra/env_vars"
